# Generated by Django 4.1.7 on 2023-02-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_enrollment_user_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Принят'),
        ),
    ]
