# Generated by Django 4.1.7 on 2023-02-19 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser__class_customuser_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='_class',
            new_name='clas_s',
        ),
    ]
