# Generated by Django 4.1.7 on 2023-02-18 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_group_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.faculty', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Номер курса'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название факультета'),
        ),
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название группы'),
        ),
    ]
