# Generated by Django 4.1.7 on 2023-02-18 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_schedule_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='schedule',
        ),
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.group'),
        ),
    ]
