# Generated by Django 4.1.7 on 2023-02-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_remove_lesson_schedule_lesson_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='day',
            field=models.CharField(choices=[('1', 'Понедельник'), ('2', 'Вторник'), ('3', 'Среда'), ('4', 'Четверг'), ('5', 'Пятница'), ('6', 'Суббота'), ('7', 'Воскресенье')], default='Понедельник', max_length=11),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
