# Generated by Django 4.1.7 on 2023-02-18 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_teacher_subject'),
        ('schedule', '0009_remove_lesson_teacher1_lesson_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.teacher'),
        ),
    ]
